apiVersion: v1
kind: Service
metadata:
 name: revisions-test
 labels:
   run: revisions-test
spec:
 type: NodePort
 ports:
   - port: 8080
     nodePort: 30001
     protocol: TCP
 selector:
   run: revisions-test